/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "lusin_store_protocol.h"
void   traffic_info__init
                     (TrafficInfo         *message)
{
  static TrafficInfo init_value = TRAFFIC_INFO__INIT;
  *message = init_value;
}
size_t traffic_info__get_packed_size
                     (const TrafficInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &traffic_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t traffic_info__pack
                     (const TrafficInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &traffic_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t traffic_info__pack_to_buffer
                     (const TrafficInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &traffic_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrafficInfo *
       traffic_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrafficInfo *)
     protobuf_c_message_unpack (&traffic_info__descriptor,
                                allocator, len, data);
}
void   traffic_info__free_unpacked
                     (TrafficInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &traffic_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor traffic_info__field_descriptors[6] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrafficInfo, timestamp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ident",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrafficInfo, ident),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_addr",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrafficInfo, source_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rule",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrafficInfo, rule),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "desc",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrafficInfo, desc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrafficInfo, amount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned traffic_info__field_indices_by_name[] = {
  5,   /* field[5] = amount */
  4,   /* field[4] = desc */
  1,   /* field[1] = ident */
  3,   /* field[3] = rule */
  2,   /* field[2] = source_addr */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange traffic_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor traffic_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TrafficInfo",
  "TrafficInfo",
  "TrafficInfo",
  "",
  sizeof(TrafficInfo),
  6,
  traffic_info__field_descriptors,
  traffic_info__field_indices_by_name,
  1,  traffic_info__number_ranges,
  (ProtobufCMessageInit) traffic_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};