/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_protocol_2eproto__INCLUDED
#define PROTOBUF_C_protocol_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _TrafficInfo TrafficInfo;


/* --- enums --- */


/* --- messages --- */

struct  _TrafficInfo
{
  ProtobufCMessage base;
  int64_t timestamp;
  char *ident;
  char *source_addr;
  char *rule;
  char *desc;
  float amount;
};
#define TRAFFIC_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&traffic_info__descriptor) \
    , 0, NULL, NULL, NULL, NULL, 0 }


/* TrafficInfo methods */
void   traffic_info__init
                     (TrafficInfo         *message);
size_t traffic_info__get_packed_size
                     (const TrafficInfo   *message);
size_t traffic_info__pack
                     (const TrafficInfo   *message,
                      uint8_t             *out);
size_t traffic_info__pack_to_buffer
                     (const TrafficInfo   *message,
                      ProtobufCBuffer     *buffer);
TrafficInfo *
       traffic_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   traffic_info__free_unpacked
                     (TrafficInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TrafficInfo_Closure)
                 (const TrafficInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor traffic_info__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_protocol_2eproto__INCLUDED */